services:
  web:
    depends_on:
      api:
        condition: service_healthy
    build:
      context: ./frontend
      target: development
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - 5173:5173
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
      target: dev
    ports:
      - 5000:8080
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/src
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
