import { type ApplicationCardType } from "#/applications";

export const applicationCardsConstant: ApplicationCardType[] = [
  {
    id: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    status: "Applied",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    salary: "$150,000 - $200,000",
    frameworksOrLanguagesUsed: "React, TypeScript, Node.js",
    contacts: "John Doe - john.doe@google.com",
    deadline: "2025-07-15",
    jobDescription: "Build scalable web applications using modern technologies",
    resumeUsed: "resume_v3.pdf",
    coverLetterUsed: "cover_letter_google.pdf",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
  },
  {
    id: "2",
    companyName: "Microsoft",
    companyEmail: "hiring@microsoft.com",
    position: "React Developer",
    link: "https://careers.microsoft.com/jobs/456",
    status: "Interviewing",
    notes: "Had first round interview, technical round scheduled",
    location: "Seattle, WA",
    salary: "$120,000 - $160,000",
    frameworksOrLanguagesUsed: "React, JavaScript, Azure",
    contacts: "Sarah Smith - sarah.smith@microsoft.com",
    deadline: "2025-07-20",
    jobDescription: "Work on Microsoft Teams frontend applications",
    resumeUsed: "resume_v3.pdf",
    coverLetterUsed: "cover_letter_microsoft.pdf",
    type: "Hybrid",
    jobType: "Full Time",
    level: "Mid",
  },
  {
    id: "3",
    companyName: "Amazon",
    companyEmail: "jobs@amazon.com",
    position: "Software Engineer Intern",
    link: "https://amazon.jobs/en/jobs/789",
    status: "WishList",
    notes: "Planning to apply next week",
    location: "Austin, TX",
    salary: "$7,000/month",
    frameworksOrLanguagesUsed: "JavaScript, Python, AWS",
    contacts: "",
    deadline: "2025-08-01",
    jobDescription: "Summer internship program for software engineering",
    resumeUsed: "",
    coverLetterUsed: "",
    type: "OnSite",
    jobType: "Internship",
    level: "Junior",
  },
  {
    id: "4",
    companyName: "Meta",
    companyEmail: "careers@meta.com",
    position: "Frontend Engineer",
    link: "https://www.metacareers.com/jobs/101112",
    status: "Offer",
    notes: "Received offer! Need to respond by end of week",
    location: "Menlo Park, CA",
    salary: "$180,000 - $220,000",
    frameworksOrLanguagesUsed: "React, GraphQL, Relay",
    contacts: "Mike Johnson - mike.johnson@meta.com",
    deadline: "2025-07-05",
    jobDescription: "Build user interfaces for Facebook and Instagram",
    resumeUsed: "resume_v4.pdf",
    coverLetterUsed: "cover_letter_meta.pdf",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
  },
  {
    id: "5",
    companyName: "Netflix",
    companyEmail: "talent@netflix.com",
    position: "UI Engineer",
    link: "https://jobs.netflix.com/jobs/131415",
    status: "Rejected",
    notes: "Didn't pass the coding challenge",
    location: "Los Gatos, CA",
    salary: "$140,000 - $180,000",
    frameworksOrLanguagesUsed: "React, Redux, TypeScript",
    contacts: "Lisa Chen - lisa.chen@netflix.com",
    deadline: "2025-06-30",
    jobDescription: "Enhance Netflix streaming experience UI",
    resumeUsed: "resume_v3.pdf",
    coverLetterUsed: "cover_letter_netflix.pdf",
    type: "Hybrid",
    jobType: "Full Time",
    level: "Mid",
  },
  {
    id: "6",
    companyName: "Spotify",
    companyEmail: "jobs@spotify.com",
    position: "Part-time Developer",
    link: "https://www.lifeatspotify.com/jobs/161718",
    status: "Ghosted",
    notes: "Applied 3 weeks ago, no response yet",
    location: "New York, NY",
    salary: "$40/hour",
    frameworksOrLanguagesUsed: "React, Node.js, GraphQL",
    contacts: "",
    deadline: "2025-07-10",
    jobDescription: "Part-time frontend development for music features",
    resumeUsed: "resume_v3.pdf",
    coverLetterUsed: "cover_letter_spotify.pdf",
    type: "Remote",
    jobType: "Part Time",
    level: "Junior",
  },
];
