import {
  type ApplicationCreateResponseDto,
  type ApplicationStatusLabel,
} from "#/applications";

export const applicationCardsConstant: ApplicationCreateResponseDto[] = [
  {
    id: "1",
    resumeId: "1",
    coverLetterId: "1",
    userId: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    startSalary: 150,
    endSalary: 200,
    contacts: "John Doe - john.doe@google.com",
    deadline: new Date("2025-07-15"),
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-03-16"),
    jobDescription: "Build scalable web applications using modern technologies",
    status: "Applied",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
    technologiesUsed: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "1",
    resumeId: "1",
    coverLetterId: "1",
    userId: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    startSalary: 150,
    endSalary: 200,
    contacts: "John Doe - john.doe@google.com",
    deadline: new Date("2025-07-15"),
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-03-16"),
    jobDescription: "Build scalable web applications using modern technologies",
    status: "Applied",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
    technologiesUsed: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "1",
    resumeId: "1",
    coverLetterId: "1",
    userId: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    startSalary: 150,
    endSalary: 200,
    contacts: "John Doe - john.doe@google.com",
    deadline: new Date("2025-07-15"),
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-03-16"),
    jobDescription: "Build scalable web applications using modern technologies",
    status: "Applied",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
    technologiesUsed: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "1",
    resumeId: "1",
    coverLetterId: "1",
    userId: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    startSalary: 150,
    endSalary: 200,
    contacts: "John Doe - john.doe@google.com",
    deadline: new Date("2025-07-15"),
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-03-16"),
    jobDescription: "Build scalable web applications using modern technologies",
    status: "Applied",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
    technologiesUsed: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "1",
    resumeId: "1",
    coverLetterId: "1",
    userId: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    startSalary: 150,
    endSalary: 200,
    contacts: "John Doe - john.doe@google.com",
    deadline: new Date("2025-07-15"),
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-03-16"),
    jobDescription: "Build scalable web applications using modern technologies",
    status: "Applied",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
    technologiesUsed: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "1",
    resumeId: "1",
    coverLetterId: "1",
    userId: "1",
    companyName: "Google",
    companyEmail: "careers@google.com",
    position: "Senior Frontend Developer",
    link: "https://careers.google.com/jobs/123",
    notes: "Applied through referral, waiting for response",
    location: "Mountain View, CA",
    startSalary: 150,
    endSalary: 200,
    contacts: "John Doe - john.doe@google.com",
    deadline: new Date("2025-07-15"),
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-03-16"),
    jobDescription: "Build scalable web applications using modern technologies",
    status: "Applied",
    type: "Remote",
    jobType: "Full Time",
    level: "Senior",
    technologiesUsed: ["React", "TypeScript", "Node.js"],
  },
];

export const ApplicationStatusToColor: Record<ApplicationStatusLabel, string> =
  {
    "All Status": "hidden",
    Interviewing: "bg-yellow-100 text-yellow-800",
    Applied: "bg-blue-100 text-blue-800",
    Rejected: "bg-red-100 text-red-800",
    Ghosted: "bg-gray-100 text-gray-800",
    Offer: "bg-green-100 text-green-800",
    WishList: "bg-purple-100 text-purple-800",
  };
